### ISSUE TITLE
CSS Class Show

### ISSUE THREAD

**Issue by beprox-coreway** [tossnet/Blazor-Color-Picker#1]
In the CSS the class .show

.show {
	    display: block;
}

I suggest this only need be affect just the control, when we use a boostrap like dropdowns in a table, this class override the behavior 

https://getbootstrap.com/docs/4.0/components/dropdowns/

**Comment by snellface** [comment]
I'm having the exact same problem. 
It breaks many other third party extensions, not just bootstrap.

**Comment by tossnet** [comment]
I change the name of this class and send an update this day
