### ISSUE TITLE
Opening modal causes Edit Form to invoke submit function

### ISSUE THREAD

**Issue by jacobjz** [tossnet/Blazor-Color-Picker#12]
`EditForm Model="_class" OnSubmit="Submit">
            div class="mb-3">
                button class="btn btn-primary" @onclick="OpenModal">
                    div style="background-color:@color" class="buttonColor"></div> Select a Color
                /button>
                ColorPicker Title="@_localizer["Color_pick"]" IsOpened="isOpened" Closed="ClosedEvent" MyColor="@color">/ColorPicker>
            /div>
            div class="mb-3">
                button class="btn btn-primary" type="submit">Save</button>
            /div>
        /EditForm>
        
            bool isOpened = false;
    void OpenModal()
    {        
        isOpened = true;
    }

    void ClosedEvent(string value)
    {
        color = value;
        isOpened = false;
    }`

if i click open modal the submit function is being invoked from edit form :)

**Comment by tossnet** [comment]
on your button that calls up the palette, specify the `type="button"` otherwise it will be treated as a Submit button
