### ISSUE TITLE
A different Approach

### ISSUE THREAD

**Issue by ShaunCurtis** [tossnet/Blazor-Color-Picker#13]
I recently answered a question on this component.

I have used the standard picker in the past, so decided to rework yours as an `InputBase` derived input control.

You can see my code here:  https://github.com/ShaunCurtis/Blazr.ColorPicker

**Comment by tossnet** [comment]
It's an interesting idea. You could have added it, I'd have merged the code

**Comment by ShaunCurtis** [comment]
I'm always respectful of other people's coding methods and techniques.  I did it as a separate project because it's a major departure from what you already have.
