### ISSUE TITLE
Does not work in .Net 8 Blazor

### ISSUE THREAD

**Issue by RHRafi009** [tossnet/Blazor-Color-Picker#14]
I have tried using this in a .Net 8 Blazor app. But this produces something like this,
![Screenshot 2024-09-22 134142](https://github.com/user-attachments/assets/ad57a435-e0c7-4aff-9b2a-e378930d68a3)

I have just copy pasted the code from the readme and did not change anything. 
`  <ColorPicker 
      Title="My Blazor ColorPicker" 
      IsOpened="_isOpened"
      Closed="ClosedEvent"
      MyColor="@_hexCode">
  </ColorPicker>`

The render mode for the parent component is set as InteractiveAuto. 
I am not sure whether this package supports .Net 8 Blazor apps.

**Comment by tossnet** [comment]
the component has been running on .NET8 for a long time. Share a repo of your code

**Comment by RHRafi009** [comment]
HI @tossnet, You can find the code in this [repo](https://github.com/RHRafi009/BlazorColorPickerIssue). 
This is just a test repo that I have created to reproduce this issue.

**Comment by tossnet** [comment]
thanks for your repo, it's just that you didn't declare the stylesheet as indicated in the INSTALLATION section :
[https://github.com/tossnet/Blazor-Color-Picker#installation](https://github.com/tossnet/Blazor-Color-Picker#installation)
since .NET 8 it's in the app.razor file

**Comment by RHRafi009** [comment]
Thank you very much to pointing it out.
