### ISSUE TITLE
Weird display glitch when hovering over colours

### ISSUE THREAD

**Issue by dylandhall** [tossnet/Blazor-Color-Picker#6]
![image](https://user-images.githubusercontent.com/13939961/121794731-1a8e9780-cc4e-11eb-8ded-10134b50e4b3.png)

when i hover the bottom row goes to the top row, otherwise works great. Only other library i have is the blazor material design library, i don't have bootstrap etc loaded.

**Comment by dylandhall** [comment]
further to this, if you change:

```
    .color-picker-case:hover {
        border: 1px solid white;
        cursor: pointer;
    }
```

to:

```
    .color-picker-case:hover {
        width: 30px;
        height: 30px;        
        border: 1px solid white;
        cursor: pointer;
    }
```

it fixes the issue. the border was adding size causing the tiles to wrap around.

**Comment by dylandhall** [comment]
have added a PR, I hope that's ok! 

note i've only tested in chrome and firefox, also in brave but that's chromium. i'd anticipate it's the same in edge as it's also chromium. i don't have access to a mac to test safari.

**Comment by tossnet** [comment]
This problem seems to come only on Chrome. I have just modified the CSS again by indicating to draw the frame inside the color box

**Comment by dylandhall** [comment]
thank you! appreciate it

that's a much better solution too, i didn't know about that css property.
