### ISSUE TITLE
License

### ISSUE THREAD

**Issue by JayJay1989** [tossnet/Blazor-Color-Picker#8]
Hello,

Is it possible to add a license on this project? 
Currently this project falls under no-license, which means:

If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.

Thx

**Comment by tossnet** [comment]
Yes, you are right. I add this

**Comment by JayJay1989** [comment]
Can be closed now. Thanks for the fast response
